name: protfolio_web
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_builder: ^0.7.0
  url_launcher: ^6.1.11
  provider: ^6.0.5
  cloud_firestore: ^4.8.3
  firebase_core: ^2.15.0
  http: ^1.1.0
  flutter_svg: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono-Light.ttf
          weight: 300
